config/routes.rb
Rails.application.routes.draw do
  root to: "tweets#index"
  devise_for :users
  resources :users
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show]
  def index
    @tweet = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
     @tweet = Tweet.new(tweet_params)
     @tweet.user_id = current_user.id
     @tweet.save
     redirect_to tweet_path(@tweet)
  end

  def show
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R-sns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'R-sns', root_path, class: "navbar-brand" %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
 
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "マイページ", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規投稿", new_tweet_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <%= image_tag attachment_url(@user, :profile_image, :fill, 150, 100, format: "jpg", fallback: "no-image.png") %>

          <h5 class="card-title">
            <%= link_to user_path(@tweet.user) do %>
              <%= @tweet.user.username%>
            <% end %>
          </h5>
          
          <h6 class="card-subtitle mb-2 text-muted"><%= simple_format @tweet.text %></h6>
          <%= attachment_image_tag @tweet, :image %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
      <%= form_with model: @tweet, local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>

      <div class="form-group">
        <%= f.label :text %><br />
        <%= f.text_area :text, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :image %><br />
        <%= f.attachment_field :image, autofocus: true, class: "form-control" %>
      </div>
      <div>
        <%= f.submit "投稿する", class: "btn btn-primary" %>
      </div>
    <% end %>

      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <%= image_tag attachment_url(@user, :profile_image, :fill, 150, 100, format: "jpg", fallback: "no-image.png") %>

          <h5 class="card-title">
            <%= @tweet.user.username %>
          </h5>

          <h6 class="card-subtitle mb-2 text-muted"><%= simple_format @tweet.text %></h6>
          <%= attachment_image_tag @tweet, :image %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>登録情報の編集</h2>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>ユーザー名</label>
          <%= f.text_field :username, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>プロフィール</label>
          <%= f.text_area :profile, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>プロフィール画像</label>
          <%= f.attachment_field :profile_image %>
        </div>
        <div>
          <%= f.submit class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>  
  <% user.username %>
<% end %>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
            <%= image_tag attachment_url(@user, :profile_image, :fill, 150, 100, format: "jpg", fallback: "no-image.png") %>
          <h5 class="card-title"><%= current_user.username %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.profile %></h6>
          <%= link_to 'ユーザー編集', edit_user_path %>
      </div>
    </div>
    </div>
  </div>
</div>